### ISSUE TITLE
Feature Request: Invoice discount

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#311]
Feature Request: the ability to add a discount to an invoice.

_Surprised this hasn't come up already, did a quick search but couldn't see anything._

**Comment by johnnyq** [comment]
O yeah this is a good one! we could have it be a choice a percent discount or an entered number.

**Comment by aftechro** [comment]
dont forget about the credited amount on the client's account as well to be shown on the invoice as Credit and balance it with future invoices

**Comment by johnnyq** [comment]
Credit and Discounts Ill take on this one assigning to me

**Comment by johnnyq** [comment]
Closing Fixed

**Comment by PecceG2** [comment]
Hello, good morning! I'm sorry to reopen this case. I'm trying to generate a recurring invoice with a discount, and it seems the format isn't allowing this to happen.
Once the "pattern" tag is removed, it's possible to add invoices with negative prices as discounts at the UI level.
Is this expected behavior?

<img width="394" height="123" alt="Image" src="https://github.com/user-attachments/assets/eb93c83c-a44c-4059-a473-3a4682d13453" />
<img width="673" height="48" alt="Image" src="https://github.com/user-attachments/assets/aa7ed5c8-b5da-4fa4-92a2-700cd473bdcf" />

**Comment by johnnyq** [comment]
Hey @PecceG2 
There is a discount option when you edit the recurring invoice

<img width="501" height="652" alt="Image" src="https://github.com/user-attachments/assets/48f71393-49a6-492f-95bc-5aa9c8df59c5" />

**Comment by PecceG2** [comment]
Excellent, I’ll use that option in the future.
Just out of curiosity, is it possible that this used to work and was recently blocked? I seem to recall that before some updates, it was possible to enter negative numbers as values.

**Comment by PecceG2** [comment]
Great news! Thanks so much for the info 💯
