### ISSUE TITLE
Adding a new client requires Primary Contact, does not alert user

### ISSUE THREAD

**Issue by adunin** [itflow-org/itflow#433]
**Describe the bug**
Adding a new client requires a primary contact but does not alert user of the fact. Nothing happens when pressing save.

**Can you reproduce this on the demo at demo.itflow.org**
Yes

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
1. Go to 'Clients'
2. Click on 'New Client'
3. Enter 'Name'
4. Press Save (Nothing happens)

**Expected behavior**
A toast notification should appear notifying the user that a required field has not been filled out. Even better, the user could be guided directly to the field.

**Comment by johnnyq** [comment]
Thank you @adunin for your interest in ITFlow! We have been aware of this issue but forgot about it. This issue will be great for tracking. I like your expected behavior approaches especially the guided field approach. We are just not sure how to programmatically approach this just yet. Maybe even highlight contact tab in red when you hit save.
