### ISSUE TITLE
Feature Request: Ability to associate multiple logins to a single asset

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#899]
Assets and logins are a 1:1 relationship, meaning duplicate assets are created when you try to link a new login to an asset.

We should allow 1 asset to many logins.

https://forum.itflow.org/d/732-duplicate-assets-appearing

**Comment by compumatter** [comment]
I agree of course.  Thanks for adding this.  Honestly at the point it actually creates multiple assets I feel this crosses the threshold into bug territory.  For instance an employee who is charged with viewing assets but not adding credentials is left to assume they have multiples of something when of course they don't.   So the information in assets cannot be depended upon.

That said, grateful for the software and understand it's a process...

**Comment by johnnyq** [comment]
@compumatter I agree this is a bug.
In the meantime the duplicate factor can be fixed by editing each login and make sure no asset is selected for that login.
I think I will work on this over the weekend. Its been bugging me for awhile.
The only thing that might be a problematic is once we update this function it will break all the current asset login relations for everyone. The logins will still exist it just wont be linked to anything after the update.
It may be wise to make an announcement about this before we do so as well.

**Comment by compumatter** [comment]
Excellent news.  After the feature is implement we will then be able to re-link the existing logins to the asset they belong to. Is that correct?

**Comment by johnnyq** [comment]
This has been fixed, no user intervention required so @compumatter you wont have to unlink associated assets in logins and duplicates will stop showing.

51248ed84144e7c38f475ab2b651dafe6df92634
and here
eeb5cece7c48e1eef18cf1b0c4b0c2a2b0570d6e
